language: android
android:
  components:
    - tools
    - platform-tools
    - platform-tools-23.1
    - tools-25.1.6
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
 - chmod +x gradlew
script:
  ./gradlew jarRelease
  
